version: '3'
services:
  mysql:
    image: mysql:8
    tmpfs:
      - /var/lib/mysql:rw
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
      - MYSQL_DATABASE=mysqldb
    networks:
      - main
    ports:
      - "3306:3306"

  jaeger:
    image: 'jaegertracing/all-in-one:latest'
    ports:
      - '127.0.0.1:5775:5775/udp'
      - '127.0.0.1:6831:6831/udp'
      - '127.0.0.1:6832:6832/udp'
      - '127.0.0.1:5778:5778'
      - '127.0.0.1:16686:16686'
      - '127.0.0.1:14268:14268'
  
  zipkin:
    image: openzipkin/zipkin
    ports:
      - '9411:9411'

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'

  sqs:
    image: vsouza/sqs-local
    ports:
      - '9324:9324'

  dynamo:
    image: 'amazon/dynamodb-local'
    ports:
      - '8000:8000'
      
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - '4563-4599:4563-4599'
      - '8055:8080'
    environment:
      - SERVICES=${SERVICES- }
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=8080
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"

networks:
  main:
    driver: bridge
